[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "EDA"
version = "0.1.0"
description = "EDA and analysis tools for the BDD100K dataset"
authors = [
  { name="Niranjan" }
]

[tool.setuptools]
package-dir = {"" = "EDA"}
