# bdd100k.yaml
# YOLOv8 config for BDD100K (object detection only)

path: C:/Users/niran/OneDrive/Desktop/Bosch/Assignment/EDA/data

train: images/train
val: images/val

names:
  0: bike
  1: bus
  2: car
  3: motor
  4: person
  5: rider
  6: traffic light
  7: traffic sign
  8: train
  9: truck
